development:
  adapter: postgresql
  encoding: unicode
  database: signup_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: signup_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: signup_production
  pool: 5

cucumber:
  <<: *test